sad_words = ["sad", "unhappy", "angry", "miserable","攰","唔開心","好down","哎","想喊","想哭","想死","啊啊啊","ahh","難頂","頂唔順","aaaa"]

starter_encouragements = ["開心D啦~","唔好唔開心啦~","你係個好人來架!","笑下啦~","你唔係唔比面我笑比我睇下哇?","Chair Up!","唔好甘傷心啦,人生就係甘,起起落落落落落落落落落落落落落落","身為你既朋友，我會係Discord支持你~","我相信你的未來充滿希望~","我聽到了","	你說的事聽起來實在令bot都落淚","很遺憾沒人打電話來安慰你","這件事對bot來說很難理解...","我相信你的未來充滿希望!","	我很遺憾你得經歷這一切","我知道這需要時間","什麼力量幫助你撐到宜家的?","我每天都會想到你","我希望你流淚時,先濕既係我博頭","好好照顧自己,我唔想下世再來關愛你~"]

rude_words = ["屌","頂你","dllm","dnnm","pk","仆街","diu","你老母","撚","fuck","fk","phuck","你老味","閪","鳩","柒","shit","pussy","吊你","能樣","收皮","asshole","bitch","on9","on 9","NMSL","吃屎","干你","幹你","你媽死","人渣","雜種","tmd","merde","Scheiße","mutterficker","fick mich","fick dich","fungula","傻逼","cunt","faggot","wanker","雞掰","冚家","𠹌","shit","cunt","Fag","Faggot","𨳊","𨶙","𨳒"]

teachers_quotes = ["已扣除你的社會信用點數","講粗口唔代表你粗窩?","你唔會淨係識得講尼d阿哇?","你得個講字?","記缺點!","嘩你講粗口咁撚粗俗既?","尊重下你自己得唔得?","You kiss your mother with that mouth?","反彈.gif","呵呵.png","我覺得你講得唔岩","富強,民主,文明,和諧!","平等,友善,誠信,敬業!","你既自由意志就係比你用來講粗口?","罰抄社會主義核心價值3次!","你森77噢??","講粗口?小心習總捉你收棉花!","你有壓力,我有壓力!點解要講粗口?","I don't know what makes you so salty, but it really works!","Who pissed in your breakfast toady?","Oh I'm sorry, was I supposed to be offended?","I'm busy right now, can I ignore you some other time?","Roses are red, Violets are blue, God made me a cutie, but what happened to you?","I bet you were up all night trying to come up with that one~","Awww, it's so cute when you try to talk about things you don't understand~","Too bad your personality doesn't match your face~","Who let you out of the cage?","Well I could agree with you, but then we'd both be wrong!"]

poison_soup = ["你唔努力下,點知咩叫徒勞無功呢,係咪?","你睇人地好似表面上一帆風順,但係其實,佢背後,亦都係一帆風順!","你覺得人地化咗妝比你靚,但你唔知道,人地卸咗妝,不但靚過你,皮膚亦都好過你","愛笑的女孩運氣不會差,但係如果一個人運氣差,應該都笑唔出","中意人就去表白,萬一人地收你做兵呢?","時間會令一切變好,有人係肥,過耐咗就會變到好肥","如果一個人秒回你PM,可能佢只係嚮廁所玩緊DC姐","如果有人話要減肥,就代表,佢零食開始要靜靜雞偷埋來吃","所有工翻耐咗都會悶,差別只不過在於,人地悶得來,人工仲比你多!","時間可以改變一個人,以前佢唔愛你,依家佢可能憎你","上帝創造你係佢既創意,你可以活落去係你既勇氣!","白雪公主教識我地,7個7頭對你幾好,都唔夠一個靚仔既一個kiss","可以用錢解決既,都唔好用錢解決,因為你無錢","努力唔一定成功,但係唔努力真係好輕鬆","搵到GF/BF之後要對佢好D,唔好對佢甘差,始終佢已經盲咗","今日我發現,你無可能望住個天伸出條脷...既同時...睇落去似個正常人"]

hi_gif = ["https://tenor.com/view/hey-tom-hanks-forrest-gump-gif-5114770","https://tenor.com/view/bad-teeth-hi-hello-wave-gif-14630063","https://tenor.com/view/yes-man-jim-carrey-hey-hello-hi-gif-4780358","https://tenor.com/view/party-audrey-nethery-hair-flip-fabulous-kareoke-gif-10860579","https://tenor.com/view/looney-tunes-daffy-duck-hello-greetings-well-hello-there-gif-17075737","https://tenor.com/view/mr-bean-funny-hello-hi-wave-gif-3528683","https://tenor.com/view/sexy-slide-hey-flirt-gif-11431748","https://tenor.com/view/hello-hi-joker-gif-3566159","https://tenor.com/view/cat-hi-cute-paw-adorable-gif-15365720","https://tenor.com/view/hello-sexy-hi-hello-mr-bean-gif-13830351","https://tenor.com/view/sup-whats-up-cat-cool-gif-14147669","https://tenor.com/view/robin-w-illiams-whats-up-wazzup-swag-swagger-gif-5389569","https://tenor.com/view/what-what-up-hey-baby-sup-gif-15082816","https://tenor.com/view/trump-whats-up-show-gif-11747042","https://tenor.com/view/whatcha-doin-doing-whats-up-gif-14618619","https://tenor.com/view/jackie-chan-whats-up-my-nigga-no-ouch-gif-3871479"]

ynchoice = ["👍","👎"]

greet_ings = ["morning","hello","hi","ello","whatsup","早晨","bonjour","bonsoir","ciao","buongiorno","prego","grazie","おげんき","おはよう","こんにちは"," こんばんは","Salut","wtsup","wts up","whats up","whassup","hihi","嗨嗨"]

stel_la = ["熱狗", "hotdog", "hot dog", "ホットドック", "收皮", "00後"]